version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
  fedai:
    build: .
    restart: always
    command: node main.js
    env_file:
      - .env
    environment:
      NODE_ENV: production
      CHROME_BIN: /usr/bin/chromium-browser
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    depends_on:
      - mongo