# fly.toml app configuration file generated for fedai on 2024-04-23T07:13:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fedai'
primary_region = 'arn'

[build]

[[vm]]
  size = 'shared-cpu-1x'
[mounts]
  source="storage_vol"
  destination="/root/fedai/auth"